precision: 32
max_epochs: 100
num_nodes: 1
devices: 5
sync_batchnorm: True
default_root_dir: ${exp_dir}
num_sanity_val_steps: 0
limit_val_batches: 1.0
accumulate_grad_batches: 4
gradient_clip_val: 10.0
reload_dataloaders_every_n_epochs: 4
